# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x06\x65ngine\"a\n\x13\x41nalyzeVideoRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x11\n\tvideo_url\x18\x02 \x01(\t\x12\x13\n\x0bscript_text\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\"D\n\x14\x41nalyzeVideoResponse\x12,\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32\x17.engine.AnnotationEvent\"\x95\x01\n\x0f\x41nnotationEvent\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x13\n\x0btranslation\x18\x05 \x01(\t\x12&\n\x05shape\x18\x06 \x01(\x0b\x32\x17.engine.AnnotationShape\"i\n\x0f\x41nnotationShape\x12\x12\n\nshape_type\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x0e\n\x06height\x18\x05 \x01(\x02\x12\r\n\x05\x63olor\x18\x06 \x01(\t2Z\n\rEngineService\x12I\n\x0c\x41nalyzeVideo\x12\x1b.engine.AnalyzeVideoRequest\x1a\x1c.engine.AnalyzeVideoResponseB:Z8github.com/yourusername/jotclip/api/internal/grpc/engineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/yourusername/jotclip/api/internal/grpc/engine'
  _globals['_ANALYZEVIDEOREQUEST']._serialized_start=24
  _globals['_ANALYZEVIDEOREQUEST']._serialized_end=121
  _globals['_ANALYZEVIDEORESPONSE']._serialized_start=123
  _globals['_ANALYZEVIDEORESPONSE']._serialized_end=191
  _globals['_ANNOTATIONEVENT']._serialized_start=194
  _globals['_ANNOTATIONEVENT']._serialized_end=343
  _globals['_ANNOTATIONSHAPE']._serialized_start=345
  _globals['_ANNOTATIONSHAPE']._serialized_end=450
  _globals['_ENGINESERVICE']._serialized_start=452
  _globals['_ENGINESERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
