// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/engine.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ScriptText    string                 `protobuf:"bytes,3,opt,name=script_text,json=scriptText,proto3" json:"script_text,omitempty"` // empty if no script uploaded
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`                       // detected language of video/script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoRequest) Reset() {
	*x = AnalyzeVideoRequest{}
	mi := &file_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoRequest) ProtoMessage() {}

func (x *AnalyzeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *AnalyzeVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *AnalyzeVideoRequest) GetScriptText() string {
	if x != nil {
		return x.ScriptText
	}
	return ""
}

func (x *AnalyzeVideoRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AnalyzeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   []*AnnotationEvent     `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoResponse) Reset() {
	*x = AnalyzeVideoResponse{}
	mi := &file_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoResponse) ProtoMessage() {}

func (x *AnalyzeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeVideoResponse) GetAnnotations() []*AnnotationEvent {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type AnnotationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`         // mismatch | missing | comment
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // info | warning | critical
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Translation   string                 `protobuf:"bytes,5,opt,name=translation,proto3" json:"translation,omitempty"`
	Shape         *AnnotationShape       `protobuf:"bytes,6,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationEvent) Reset() {
	*x = AnnotationEvent{}
	mi := &file_proto_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationEvent) ProtoMessage() {}

func (x *AnnotationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationEvent.ProtoReflect.Descriptor instead.
func (*AnnotationEvent) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{2}
}

func (x *AnnotationEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AnnotationEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnnotationEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AnnotationEvent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AnnotationEvent) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *AnnotationEvent) GetShape() *AnnotationShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

type AnnotationShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShapeType     string                 `protobuf:"bytes,1,opt,name=shape_type,json=shapeType,proto3" json:"shape_type,omitempty"` // rect | arrow | circle
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationShape) Reset() {
	*x = AnnotationShape{}
	mi := &file_proto_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationShape) ProtoMessage() {}

func (x *AnnotationShape) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationShape.ProtoReflect.Descriptor instead.
func (*AnnotationShape) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{3}
}

func (x *AnnotationShape) GetShapeType() string {
	if x != nil {
		return x.ShapeType
	}
	return ""
}

func (x *AnnotationShape) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AnnotationShape) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AnnotationShape) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AnnotationShape) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AnnotationShape) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_proto_engine_proto protoreflect.FileDescriptor

const file_proto_engine_proto_rawDesc = "" +
	"\n" +
	"\x12proto/engine.proto\x12\x06engine\"\x8a\x01\n" +
	"\x13AnalyzeVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vscript_text\x18\x03 \x01(\tR\n" +
	"scriptText\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"Q\n" +
	"\x14AnalyzeVideoResponse\x129\n" +
	"\vannotations\x18\x01 \x03(\v2\x17.engine.AnnotationEventR\vannotations\"\xcf\x01\n" +
	"\x0fAnnotationEvent\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12 \n" +
	"\vtranslation\x18\x05 \x01(\tR\vtranslation\x12-\n" +
	"\x05shape\x18\x06 \x01(\v2\x17.engine.AnnotationShapeR\x05shape\"\x90\x01\n" +
	"\x0fAnnotationShape\x12\x1d\n" +
	"\n" +
	"shape_type\x18\x01 \x01(\tR\tshapeType\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x02R\x06height\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color2Z\n" +
	"\rEngineService\x12I\n" +
	"\fAnalyzeVideo\x12\x1b.engine.AnalyzeVideoRequest\x1a\x1c.engine.AnalyzeVideoResponseB:Z8github.com/yourusername/jotclip/api/internal/grpc/engineb\x06proto3"

var (
	file_proto_engine_proto_rawDescOnce sync.Once
	file_proto_engine_proto_rawDescData []byte
)

func file_proto_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)))
	})
	return file_proto_engine_proto_rawDescData
}

var file_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_engine_proto_goTypes = []any{
	(*AnalyzeVideoRequest)(nil),  // 0: engine.AnalyzeVideoRequest
	(*AnalyzeVideoResponse)(nil), // 1: engine.AnalyzeVideoResponse
	(*AnnotationEvent)(nil),      // 2: engine.AnnotationEvent
	(*AnnotationShape)(nil),      // 3: engine.AnnotationShape
}
var file_proto_engine_proto_depIdxs = []int32{
	2, // 0: engine.AnalyzeVideoResponse.annotations:type_name -> engine.AnnotationEvent
	3, // 1: engine.AnnotationEvent.shape:type_name -> engine.AnnotationShape
	0, // 2: engine.EngineService.AnalyzeVideo:input_type -> engine.AnalyzeVideoRequest
	1, // 3: engine.EngineService.AnalyzeVideo:output_type -> engine.AnalyzeVideoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_engine_proto_init() }
func file_proto_engine_proto_init() {
	if File_proto_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_proto_depIdxs,
		MessageInfos:      file_proto_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_proto = out.File
	file_proto_engine_proto_goTypes = nil
	file_proto_engine_proto_depIdxs = nil
}
